paths:
  /movies:
    get:
      tags:
      - "movies"
      summary: "Gets a list of movies"
      description: "List movies"
      operationId: "listMovies"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MovieList"
        500:
          description: "Internal error"
tags:
- name: "movies"
  description: "Endpoints for movies"
  externalDocs:
    description: "This endpoint comes from themoviedb.org"
    url: "http://localhost"
definitions:
  MovieList:
    type: "object"
    properties:
      page:
        type: "integer"
      total_results:
        type: "integer"
      total_pages:
        type: "integer"
      results:
        type: "array"
        items:
          type: "object"
          properties:
            title:
              type: "string"
            poster_path:
              type: "string"
            release_date:
              type: "string"