swagger: "2.0"
info:
  description: "This is the swagger documentation for the UnoSquare test"
  version: "1.0.0"
  title: "UnoSquare test"
host: "localhost:3000"
basePath: "/api/v1"
schemes:
- "http"